### ISSUE TITLE
0.1.6 error

### ISSUE THREAD

**Issue by ericdp** [Percona-Lab/mysql_random_data_load#7]
create a smaller table then in the example.

`
mysql> CREATE TABLE eric.t2(
  id      INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  t       TIME DEFAULT NULL,
  vc10    VARCHAR(10),
  vc25    VARCHAR(25),
  vc100   VARCHAR(100),
  ts      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  dt      DATETIME DEFAULT NULL,
  e       ENUM( 'x', 'a', 'b', 'c', 'd', 'e', 'f' ) NOT NULL
)
ENGINE = InnoDB
DEFAULT CHARSET = utf8mb4
DEFAULT COLLATE = utf8mb4_0900_as_cs;
`

try to add some data and get the following INFO error.  no data in the table.

`
$ mysql_random_data_loader --host="127.0.0.1" --user=root --password=xxx eric t2 500
INFO[0000] cannot get table t2 struct: cannot read indexes: sql: expected 14 destination arguments in Scan, not 13
`

I'm on a Mac with mysql v.8.0.3

**Comment by agustin-percona** [comment]
Hi Eric,

I can confirm that this is an issue with mysql 8.0.3. I tried with 5.7 (without `COLLATE = utf8mb4_0900_as_cs`) and it's working as expected.

This is because in 8.0 we now have the `VISIBLE` column added:
```
mysql [localhost] {msandbox} (test) > show indexes from table1\G
*************************** 1. row ***************************
        Table: table1
   Non_unique: 0
     Key_name: PRIMARY
 Seq_in_index: 1
  Column_name: id
    Collation: A
  Cardinality: 0
     Sub_part: NULL
       Packed: NULL
         Null: 
   Index_type: BTREE
      Comment: 
Index_comment: 
      Visible: YES
1 row in set (0.00 sec)
```

We'll review and make the necessary changes to support 8.0. Thanks for the report!

**Comment by guriandoro** [comment]
Hi Eric,

I can confirm that this is an issue with mysql 8.0.3. I tried with 5.7 (without `COLLATE = utf8mb4_0900_as_cs`) and it's working as expected.

This is because in 8.0 we now have the `VISIBLE` column added:
```
mysql [localhost] {msandbox} (test) > show indexes from table1\G
*************************** 1. row ***************************
        Table: table1
   Non_unique: 0
     Key_name: PRIMARY
 Seq_in_index: 1
  Column_name: id
    Collation: A
  Cardinality: 0
     Sub_part: NULL
       Packed: NULL
         Null: 
   Index_type: BTREE
      Comment: 
Index_comment: 
      Visible: YES
1 row in set (0.00 sec)
```

We'll review and make the necessary changes to support 8.0. Thanks for the report!
